apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server-metadata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
        - name: nginx-server
          image: nginx:latest
          ports:
            - containerPort: 80
